CREATE DATABASE BODEGA;
USE BODEGA;
CREATE TABLE VINICOLA (
COD_VINICOLA BIGINT NOT NULL AUTO_INCREMENT,
NOME_VINICOLA VARCHAR (100) NOT NULL,
DESCRICAO_VINICOLA TEXT NOT NULL,
FONE_VINICOLA VARCHAR (15) NOT NULL,
EMAIL_VINICOLA VARCHAR (45) NOT NULL,
COD_REGIAO BIGINT NOT NULL,
PRIMARY KEY (COD_VINICOLA)
);

CREATE TABLE VINHO (
COD_VINHO BIGINT NOT NULL AUTO_INCREMENT,
NOME_VINHO VARCHAR (50) NOT NULL,
TIPO_VINHO VARCHAR (30) NOT NULL,
ANO_VINHO INT NOT NULL,
DESCRICAO_VINHO TEXT NOT NULL,
COD_VINICOLA BIGINT NOT NULL,
PRIMARY KEY (COD_VINHO)
);

CREATE TABLE REGIAO (
COD_REGIAO BIGINT NOT NULL AUTO_INCREMENT,
NOME_REGIAO VARCHAR (100) NOT NULL,
DESCRICAO_REGIAO TEXT NOT NULL,
PRIMARY KEY (COD_REGIAO)
);

ALTER TABLE bodega.vinho 
ADD CONSTRAINT FK_VINHO_CODVINICOLA
  FOREIGN KEY (COD_VINICOLA)
  REFERENCES bodega.vinicola (COD_VINICOLA);
  
ALTER TABLE bodega.vinicola 
ADD CONSTRAINT FK_VINICOLA_CODREGIAO
  FOREIGN KEY (COD_REGIAO)
  REFERENCES bodega.REGIAO (COD_REGIAO);

-- DROP SCHEMA BODEGA;

SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO BODEGA.VINICOLA
(NOME_VINICOLA, DESCRICAO_VINICOLA, FONE_VINICOLA, EMAIL_VINICOLA, COD_REGIAO)
VALUES
('CASA VALDUGA', 'ESPECIALISTA EM TERROIR MERLOT.', '4196385252','CASAVALDUGA@VINICOLA.COM', 1),
('PIZZATO',	'ESPECIALISTA EM VINHO RESERVA MERLOT',	'4196385253',	'PIZZATO@VINICOLA.COM', 2),
('CAVE AMADEU',	'ESPECIALISTA EM VINHO ESPUMANTE.',	'4196385254',	'CAVEAMADEU@VINICOLA.COM', 3),
('DON GIOVANNI',	'ESPECIALISTA EM VINHO CHARDONNAY.',	'4196385255',	'DONGIOVANNI@VINICOLA.COM', 4),
('CASA PERINI',	'ESPECIALISTA EM VINHO MOSCATEL.',	'4196385256',	'CASAPERINI@VINICOLA.COM', 5);

INSERT INTO BODEGA.REGIAO
(NOME_REGIAO, DESCRICAO_REGIAO)
VALUES
('Vale dos Vinhedos', 'Melhor Terroir da região em um Merlot encorpado.'),
('Vale dos Vinhedos', 'Melhor Terroir da região.'),
('Vale dos Vinhedos', 'Melhor Espumante da região.'),
('Vale dos Vinhedos', 'Melhor Chardonnay da região.'),
('Vale dos Vinhedos', 'Melhor Moscatel da região.');

INSERT INTO BODEGA.VINHO
(NOME_VINHO, TIPO_VINHO, ANO_VINHO, DESCRICAO_VINHO, COD_VINICOLA)
VALUES
('IDENTIDADE', 'BRANCO SECO', 2012, 'HARMONIZAÇÃO PEIXES', 1),
('LE VIN', 'ROSE', 2010, 'HARMONIZAÇÃO SALADAS', 2),
('CANTINERI', 'LAMBRUSCO', 2005, 'HARMONIZAÇÃO SOBREMESAS', 3),
('DON SIMON', 'BRANCO DEMI SEC', 2020, 'HARMONIZAÇÃO PEIXES', 4),
('BELHARA', 'TINTO SUAVE', 2015, 'HARMONIZAÇÃO PIZZA E MASSAS', 5);

-- Faça uma consulta que liste o nome e ano dos  vinhos, incluindo o nome da vinícula e o nome da região que ela pertence;

SELECT VINHO.NOME_VINHO,
	VINHO.ANO_VINHO,
    VINICOLA.NOME_VINICOLA,
    REGIAO.NOME_REGIAO
FROM VINHO INNER JOIN VINICOLA
ON VINICOLA.COD_VINICOLA = VINHO.COD_VINICOLA
INNER JOIN REGIAO
ON VINICOLA.COD_REGIAO = REGIAO.COD_REGIAO;
 

-- CONSULTA DADOS

SELECT * FROM VINICOLA;
SELECT * FROM VINHO;
SELECT * FROM REGIAO;

-- CRIA USUÁRIOS

create user somellier1 identified by "vinicola" with max_connections_per_hour 40;
grant select on table vinho to somellier1;
grant select on table vinicola to somellier1;
grant show view on table vinicola to somellier1;
grant select (COD_VINICOLA), show view  on VINICOLA to somellier1;
grant select (NOME_VINICOLA), show view on VINICOLA to somellier1;

-- revoke show view ON bodega.vinicola from somellier1;